server:
  port: 7071

spring:
  application:
    name: "Student Application"
  datasource-primary:
    url: jdbc:mysql://localhost:3306/studentdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: #password
  datasource-secondary:
    url: jdbc:mysql://localhost:3306/studentdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: #password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
    health:
      show-details: always

info:
  application:
    name: "Student Application"
    database: "MySQL"